version: '3.3'
services:
  # storage
  elasticsearch:
    image: elasticsearch:6.8.16
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
#      - ./elasticsearch/data:/usr/share/elasticsearch/data
#      - /etc/localtime:/etc/localtime
  # server
  oap:
    image: apache/skywalking-oap-server:8.6.0-es6
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
      - 1234:1234
    environment:
      SW_STORAGE: elasticsearch # 默认为es6，es7为elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
#    volumes:
#      - /etc/localtime:/etc/localtime
  # dashboard
  ui:
    image: apache/skywalking-ui:8.6.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
#    volumes:
#      - /etc/localtime:/etc/localtime